# Generated by Django 4.2.3 on 2023-09-09 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inmuebleslist_app', '0005_alter_comentario_edificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='comentario_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
